import requests
import os
import json

from datetime import datetime
from dotenv import find_dotenv, load_dotenv

dotenv_path = find_dotenv()  # find .env file
load_dotenv(dotenv_path)  # load .env file as environment variables

user_api = os.getenv("api-key")
location = input("Enter the city name: ")

with open('languages.json') as f: #open json file and store language codes
    language_codes = json.load(f)

lang = input("Enter the language: ").casefold() #input language and convert to lowercase
lang_code = language_codes.get(lang)

if lang_code:
    complete_api_link = f"https://api.openweathermap.org/data/2.5/weather?q={location}&appid={user_api}&lang={lang_code}"
else:
    print("Invalid language. Defaulting to English.")
    complete_api_link = f"https://api.openweathermap.org/data/2.5/weather?q={location}&appid={user_api}&lang=en" #print (complete_api_link) in English

api_link = requests.get(complete_api_link)
api_data = api_link.json()
print(api_data) #checking translation

if api_data['cod']=='404':
    print ("-------------------------------------------------------------")
    print ("Invalid City: {}, Please check your City name".format(location))
    print ("-------------------------------------------------------------")


else:
    #create variables to store and display data
    temp_city = ((api_data['main']['temp']) - 273.15)
    weather_desc = api_data['weather'][0]['description']
    hmdt = api_data['main']['humidity']
    wind_spd = api_data['wind']['speed']
    date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

    print ("-------------------------------------------------------------")
    print ("Weather Stats for - {}  || {}".format(api_data['name'].upper(), date_time))
    print ("-------------------------------------------------------------")
    print ("Current temperature is: {:.2f} deg C".format(temp_city))
    print ("Current weather desc :",weather_desc)
    print ("Current Humidity :",hmdt, '%')
    print ("Current wind speed :",wind_spd ,'kmph')
    print ("-------------------------------------------------------------")

    print ("-------------------------------------------------------------")
    print ("This weather report is generated by Shreyan")
    print ("-------------------------------------------------------------")